name: Build_x86_64

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt -y install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "Asia/Shanghai"

    - name: Checkout Own Repository
      uses: actions/checkout@v4    
    
    - name: Checkout Openwrt Official
      uses: actions/checkout@v4
      with: 
        repository: openwrt/openwrt
        path: openwrt
      
    - name: check space
      run: |
        df -h
        
    - name: Set Proxy Plugin
      run: |
        echo "src-git ssrp https://github.com/fw876/helloworld.git" >> openwrt/feeds.conf.default
        echo "src-git passwall2 https://github.com/xiaorouji/openwrt-passwall2.git;main" >> openwrt/feeds.conf.default
        echo "src-git passwall_packages https://github.com/xiaorouji/openwrt-passwall-packages.git;main" >> openwrt/feeds.conf.default
        git clone --depth 1 -b master --single-branch https://github.com/vernesong/OpenClash.git && mv OpenClash/luci-app-openclash openwrt/package/luci-app-openclash    
    
    - name: Update & Install feeds
      run: |
        openwrt/scripts/feeds clean
        openwrt/scripts/feeds update -a
        openwrt/scripts/feeds install -a

    - name: Configure default settings
      run: |
        mkdir -p openwrt/files/etc/uci-defaults
        cat << "EOF" > openwrt/files/etc/uci-defaults/99-custom
        uci -q set network.lan.ipaddr='10.103.0.1'
        EOF

    - name: Configuration Customization - Build_x86_64
      env:
        CONFIG_FILE: 'x86_64.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
        cd openwrt && make defconfig
    
    - name: check space
      run: |
        df -h
    
    - name: Build firmware
      working-directory: ./openwrt
      run: |
        echo -e "$(nproc) thread build."
        make -j$(nproc) defconfig download clean world

    - name : Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: OpenWrt
        path: openwrt/bin
